name: PreBuild Site

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
    paths:
      - 'posts/**'

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Lint JSON
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_JSON: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Add Posts to HTML
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./build-posts-script.js');
            const main = await script.main;
            console.log(main);
            return main;
            
      - name: Lint HTML
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_HTML: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push HTML to deploy branch
        run: |
          git config --global user.email ${{ env.email }}
          git config --global user.name ${{ env.user }}
          git stash
          git checkout gh-pages
          git stash pop
          git add index.html
          git commit -m "add posts"
          git status -v
          git push origin
        env:
          email: 32312177+Dangey@users.noreply.github.com
          user: Dangey
          
